### PR TITLE
Using TypeRuntimeWiring for newTypeWiring

### PR DESCRIPTION
**Pull request by dushyant89**

### CODE REVIEW

**Comment by johnliucn925** [comment]
Currently it is using static import to use TypeRuntimeWiring.newTypeWiring, It is same as your change. Do I miss anything?

**Comment by dushyant89** [comment]
You are right @johnliucn925, the code is correct but i suggested this change because if you are building the code from the [tutorial](https://www.graphql-java.com/tutorials/getting-started-with-spring-boot/) the IDE imports the files automatically but since the method `newTypeWiring` has a static import so you are not able to figure that out until you come to this repo. It's just for the convenience.

**Comment by TusharGirase** [comment]
Are we going to merge this pull request?

**Comment by dondonz** [comment]
Hello, thanks for submitting the PR and sorry for leaving you hanging for such a long time.

As the tutorial has changed quite a bit since to use Spring for GraphQL, I will close this PR

**Pull request closed without merging**
